# FROM nginx:1.16.0-alpine
# COPY ./build /usr/share/nginx/html
# RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.disabled
# COPY ./docker/nodeapp.conf /etc/nginx/conf.d/nodeapp.conf
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]

FROM node:10

# Create app directory
WORKDIR /usr/src/app


# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY ./src ./src
COPY ./public ./public

# ADD docker/wait-for-it.sh /wait-for-it.sh
# RUN bash -c 'chmod 777 /wait-for-it.sh'

EXPOSE 3000
CMD [ "npm", "run", "start" ]