version: "3"

services:
  solr:
    image: arm32v5/solr:5-slim
    labels:
      NAME: "solr"
    hostname: "solr"
    container_name: "solr"
    ports:
     - "9983:9983"
     - "8983:8983"
    volumes:
      - ./data/solr/solr:/opt/solr/server/solr
      # - ./data/Solr/data/:/var/solr/data/
      # - ./data/Solr/configsets/:/opt/solr/server/solr/configsets/
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -c
      - -f
  # redis:
  #   image: redis
  #   container_name: cache
  #   ports:
  #     - "6379:6379"

  web-app:
    build: server/.
    #working_dir: /
    labels:
      NAME: "node"
    hostname: "node"
    container_name: "node"
    image: node-server-app:1.0
    entrypoint: -- /wait-for-it.sh solr:8983 -t 120 --
    command: npm run server
    ports:
      - "5000:5000"
    volumes: 
      - ./server/:/usr/src/app
    environment:
      - SOLR_SERVICE_HOST=solr
    links:
      - solr
    depends_on:
      - solr   

  auth-app:
    build: authserver/.
    #working_dir: /
    labels:
      NAME: "authserver"
    hostname: "authserver"
    container_name: "authserver"
    image: auth-server-app:1.0
    command: npm run server
    ports:
      - "9000:9000"
    volumes: 
      - ./authserver/:/usr/src/app
  
  acc-app:
    build: accserver/.
    #working_dir: /
    labels:
      NAME: "accserver"
    hostname: "accserver"
    container_name: "accserver"
    image: acc-server-app:1.0
    command: npm run server
    ports:
      - "7000:7000"
    volumes: 
      - ./accserver/:/usr/src/app
    environment:
      - AUTH_SERVICE_HOST=authserver

  checkout-app:
    build: checkoutserver/.
    #working_dir: /
    labels:
      NAME: "checkoutserver"
    hostname: "checkoutserver"
    container_name: "checkoutserver"
    image: checkoutserver-server-app:1.0
    command: npm run server
    ports:
      - "8000:8000"
    volumes: 
      - ./checkoutserver/:/usr/src/app

  frontend-app:
    build: client/.
    labels:
      NAME: "react"
    hostname: "react"
    container_name: "react"
    image: react-server-app:1.0
    ports:
      - "3000:3000"
    volumes: 
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
    links:
      - solr
    depends_on:
      - solr

  lb-app:
    build: nginx/.
    labels:
      NAME: "nginx"
    hostname: "nginx"
    image: nginx-app:1.0
    ports:
      - "80:80"
    links:
      - web-app
      - frontend-app
    depends_on:
      - web-app
      - frontend-app

  dataloader-app:
    build: dataload/.
    labels:
      NAME: "dataload"
    hostname: "dataload"
    container_name: dataload
    image: dataload-app:1.0
    environment:
      - SOLR_SERVICE_HOST=solr
      - MONGO_SERVICE_HOST=mongo

  # mongo-express :
  #   image : mongo-express
  #   ports :
  #     - "8081:8081"
  #   environment :
  #     - ME_CONFIG_BASICAUTH_USERNAME=root
  #     - ME_CONFIG_BASICAUTH_PASSWORD=example
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=example
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #   links :
  #     - mongo
  #   depends_on: 
  #     - mongo