version: "3"

services:
  mongo:
    image: mongo:latest
    labels:
      NAME: "mongo"
    hostname: "mongo"
    container_name: "mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes: 
      - ./data/mongoData:/data/db
  
  solr:
    image: solr:8
    labels:
      NAME: "solr"
    hostname: "solr"
    container_name: "solr"
    ports:
     - "9983:9983"
     - "8983:8983"
    # volumes:
    #   - ./data/solr:/var/solr
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -c
      - -f

  web-app:
    build: server/.
    #working_dir: /
    labels:
      NAME: "node"
    hostname: "node"
    container_name: "node"
    image: node-server-app:1.0
    # entrypoint: ./wait-for-it.sh mongo:27017 solr:9983 -t 120 --
    ports:
      - "5000:5000"
    volumes: 
      - ./server/:/usr/src/app
    environment:
      - SOLR_SERVICE_HOST=solr
      - MONGO_SERVICE_HOST=mongo
    links:
      - mongo
      - solr
    depends_on:
      - mongo
      - solr   

  auth-app:
    build: authserver/.
    #working_dir: /
    labels:
      NAME: "authserver"
    hostname: "authserver"
    container_name: "authserver"
    image: auth-server-app:1.0
    # entrypoint: ./wait-for-it.sh mongo:27017 solr:9983 -t 120 --
    ports:
      - "9000:9000"
    volumes: 
      - ./authserver/:/usr/src/app
    environment:
      - MONGO_SERVICE_HOST=mongo
  
  acc-app:
    build: accserver/.
    #working_dir: /
    labels:
      NAME: "accserver"
    hostname: "accserver"
    container_name: "accserver"
    image: acc-server-app:1.0
    # entrypoint: ./wait-for-it.sh mongo:27017 solr:9983 -t 120 --
    ports:
      - "7000:7000"
    volumes: 
      - ./accserver/:/usr/src/app
    environment:
      - MONGO_SERVICE_HOST=mongo
      - AUTH_SERVICE_HOST=authserver

  checkout-app:
    build: checkoutserver/.
    #working_dir: /
    labels:
      NAME: "checkoutserver"
    hostname: "checkoutserver"
    container_name: "checkoutserver"
    image: checkoutserver-server-app:1.0
    # entrypoint: ./wait-for-it.sh mongo:27017 solr:9983 -t 120 --
    ports:
      - "8000:8000"
    volumes: 
      - ./checkoutserver/:/usr/src/app
    environment:
      - MONGO_SERVICE_HOST=mongo

  frontend-app:
    build: client/.
    labels:
      NAME: "react"
    hostname: "react"
    container_name: "react"
    image: react-server-app:1.0
    ports:
      - "3000:3000"
    volumes: 
      - ./client/src:/usr/src/app/src
    links:
      - mongo
      - solr
    depends_on:
      - mongo
      - solr

  lb-app:
    build: nginx/.
    labels:
      NAME: "nginx"
    hostname: "nginx"
    image: nginx-app:1.0
    ports:
      - "80:80"
    links:
      - web-app
      - frontend-app
    depends_on:
      - web-app
      - frontend-app

  dataloader-app:
    build: dataload/.
    labels:
      NAME: "dataload"
    hostname: "dataload"
    container_name: dataload
    image: dataload-app:1.0
    environment:
      - SOLR_SERVICE_HOST=solr
      - MONGO_SERVICE_HOST=mongo

  # mongo-express :
  #   image : mongo-express
  #   ports :
  #     - "8081:8081"
  #   environment :
  #     - ME_CONFIG_BASICAUTH_USERNAME=root
  #     - ME_CONFIG_BASICAUTH_PASSWORD=example
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=MongoDB2019!
  #   links :
  #     - mongo
  #   depends_on: 
  #     - mongo