FROM nginx:1.16.0-alpine
# COPY ./build /usr/share/nginx/html
RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.disabled
COPY ./nodeapp.conf /etc/nginx/conf.d/nodeapp.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]