
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-react
  labels:
    app: ecom-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactpod
  template:
    metadata:
      labels:
        app: reactpod
    spec:
      containers:
        - name: reactcontainer
          image: react-server-app:1.0
          ports:
            - containerPort: 3000
          imagePullPolicy: Never
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-node
  labels:
    app: ecom-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodepod
  template:
    metadata:
      labels:
        app: nodepod
    spec:
      containers:
        - name: nodecontainer
          image: node-server-app:1.0
          ports:
            - containerPort: 5000
          env:
            - name: SOLR_HOST
              value: solr
            - name: MONGODB_HOST
              value: mongo
          imagePullPolicy: Never

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-solr
  labels:
    app: ecom-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solrpod
  template:
    metadata:
      labels:
        app: solrpod
    spec:
      containers:
        - name: solrcontainer
          image: solr:latest
          ports:
            - containerPort: 8983
            - containerPort: 9983
          args:
            - docker-entrypoint.sh
            - solr
            - start
            - -c
            - -f

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-mongo
  labels:
    app: ecom-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongopod
  template:
    metadata:
      labels:
        app: mongopod
    spec:
      containers:
        - name: mongocontainer
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-nginx
  labels:
    app: ecom-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxpod
  template:
    metadata:
      labels:
        app: nginxpod
    spec:
      containers:
        - name: nginxcontainer
          image: nginx-app:1.0
          ports:
            - containerPort: 80
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: nodepod
---
apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: reactpod
---
apiVersion: v1
kind: Service
metadata:
  name: solr
spec:
  ports:
  - name: solr
    port: 8983
    targetPort: 8983
  - name: zookeeper
    port: 9983
    targetPort: 9983
  selector:
    app: solrpod
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongopod
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginxpod
  type: LoadBalancer